Traceback (most recent call last):
  File "c:\Python\NF_2024\quick_draw\transformer_train.py", line 57, in <module>
    pred_gen, pred_stop = model(X, src_mask)  # 推論（forward）
                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\chiba\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python\NF_2024\quick_draw\models\transformer.py", line 80, in forward
    output = self.transformer_decoder(src, src, tgt_mask = src_mask)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chiba\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TransformerEncoder.forward() got an unexpected keyword argument 'tgt_mask'
